# Generated by Django 6.1 on 2026-08-18 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre comercial del producto.', max_length=150, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion breve del producto.', max_length=500, verbose_name='descripcion')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos. No admite valores negativos.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='producto_precio_no_negativo')],
            },
        ),
    ]
